# Generated by Django 5.0.3 on 2024-03-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=None, unique=True, upload_to='products/'),
            preserve_default=False,
        ),
    ]
